Controllers/CarController.cs
using Microsoft.AspNetCore.Mvc;
using Car_Rental_System.Models;
using Car_Rental_System.Repositories;
using System.Diagnostics;

namespace Car_Rental_System.Controllers
{
    public class CarController : Controller
    {
        private IWebHostEnvironment webHostEnvironment;
        public CarController(IWebHostEnvironment webHostEnvironment)
        {
            this.webHostEnvironment = webHostEnvironment;
        }
        public IActionResult Index()
        {

            List<Car> cars = Data.GetAllCars();
            return View(cars);
        }


        public IActionResult Add()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Add(Car c) {
            if (c is null)
            {
                Debug.WriteLine("Null problem");
            }
            else {

                Models.CarRentalSystemContext db =  Models.CarRentalSystemContext.Instance;
                Data data = new Data(webHostEnvironment);
                Car newcar = new Car() {
                SeatingCapacity = c.SeatingCapacity,
                Model = c.Model,
                CarNumber = c.CarNumber,
                ImagePath = data.saveImage(c.CarImage),
                Brand = c.Brand,
                Engine = c.Engine,
                PassingYear=c.PassingYear,
                FuelType = c.FuelType ,
                };
                
                db.Cars.Add(newcar);
                db.SaveChanges();
                Debug.WriteLine("done");
            }
            

            return RedirectToAction("Index");
        }
    }
}

Controllers/DriverController.cs
using Car_Rental_System.Models;
using Car_Rental_System.Repositories;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Car_Rental_System.Controllers
{
    public class DriverController : Controller
    {
        private IWebHostEnvironment webHostEnvironment;
        public DriverController(IWebHostEnvironment webHostEnvironment)
        {
            this.webHostEnvironment = webHostEnvironment;
        }
        public IActionResult Index()
        {
            List<Driver> drivers = Data.GetAllDrivers();
           
            return View(drivers);
        }

        public IActionResult Add()
        {
            return View();  
        }

        [HttpPost]
        public IActionResult Add(Driver driver) {

            if (driver is null)
            {
                Debug.WriteLine("Null problem");
            }
            else
            {

                Models.CarRentalSystemContext db =  Models.CarRentalSystemContext.Instance;
                Data data = new Data(webHostEnvironment);
                Driver newdriver = new Driver()
                {
                    DriverName=driver.DriverName,
                    Age=driver.Age,
                    Address=driver.Address,
                    Experience=driver.Experience,
                    MobileNumber=driver.MobileNumber,
                    ImagePath = data.SaveDriverImage(driver.DriverImage),
                    
                };

                db.Drivers.Add(newdriver);
                db.SaveChanges();
                Debug.WriteLine("done");
            }


            return RedirectToAction("Index");
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet"/>

</head>
<body>


    <nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">
       
            <div class="container-fluid">
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            @Html.ActionLink("Home", "Index", "Home", null, new { @class = "nav-link " })

                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("Cars", "Index", "Car", null, new {@class="nav-link "})
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("Drivers","Index","Driver",null, new { @class = "nav-link " })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("Rent", "Index", "Rent", null, new { @class = "nav-link " })

                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("Contact Us", "Contact", "Home", null, new { @class = "nav-link " })

                        </li>

                    </ul>
                    
                </div>
            </div>
    </nav>





    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-4 offset-1 col-sm-2">
                        <h5>Links</h5>
                        <ul class="list-unstyled">
                            <li>@Html.ActionLink("Home", "Index", "Home", null, new { @class = "" })</li>
                            <li> @Html.ActionLink("Cars", "Index", "Car", null, new {@class=""})</li>
                            <li> @Html.ActionLink("Rent", "Index", "Rent", null, new { @class = "" })</li>
                            <li>@Html.ActionLink("Contact Us", "Contact", "Home", null, new { @class = "" })</li>
                        </ul>
                    </div>
                    <div class="col-7 col-sm-5">
                        <h5>Our Address</h5>
                        <address>
                            121, Clear Water Bay Road<br />
                            Clear Water Bay, Kowloon<br />
                            HONG KONG<br />
                            <i class="fa fa-phone fa-lg"></i>: +852 1234 5678<br />
                            <i class="fa fa-fax fa-lg"></i>: +852 8765 4321<br />
                            <i class="fa fa-envelope fa-lg"></i>: <a href="mailto:confusion@rentCar.net">
                                confusion@rentCar.net
                            </a>
                        </address>
                    </div>
                    <div class="col-12 col-sm-4 align-self-center">
                        <div class="text-center">
                            <a class="btn btn-social-icon btn-google" href="http://google.com/+"><i class="fa fa-google-plus"></i></a>
                            <a class="btn btn-social-icon btn-facebook" href="http://www.facebook.com/profile.php?id="><i class="fa fa-facebook"></i></a>
                            <a class="btn btn-social-icon btn-linkedin" href="http://www.linkedin.com/in/"><i class="fa fa-linkedin"></i></a>
                            <a class="btn btn-social-icon btn-twitter" href="http://twitter.com/"><i class="fa fa-twitter"></i></a>
                            <a class="btn btn-social-icon btn-google" href="http://youtube.com/"><i class="fa fa-youtube"></i></a>
                            <a class="btn btn-social-icon" href="mailto:"><i class="fa fa-envelope-o"></i></a>
                        </div>
                    </div>
                </div>
                <div class="row justify-content-center">
                    <div class="col-auto">
                        <p>© Copyright 2022 </p>
                    </div>
                </div>
            </div>

        </footer>
    </div>

    @*@Scripts.Render("~/bundles/jquery")*@
    @*@Scripts.Render("~/bundles/bootstrap")*@
    @RenderSection("scripts", required: false)
</body>
</html>